name: Deploy after push
run-name: Deploy to gh-pages
on:
  push:
    branches:
      - master
jobs:
  deploy-job:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        env:
          REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
          REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
          REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
          REACT_APP_SENDER_ID: ${{secrets.REACT_APP_SENDER_ID}}
          REACT_APP_API_ID: ${{secrets.REACT_APP_API_ID}}
        run: |
          npm run build
          npm run deploy
